#!/usr/bin/env bash
set -euo pipefail

export TRICHAT_BRIDGE_DRY_RUN="${TRICHAT_BRIDGE_DRY_RUN:-1}"
export TRICHAT_DOGFOOD_EXECUTE="${TRICHAT_DOGFOOD_EXECUTE:-1}"
export TRICHAT_DOGFOOD_CYCLES="${TRICHAT_DOGFOOD_CYCLES:-1}"
export TRICHAT_DOGFOOD_KEEP_ACTIVE="${TRICHAT_DOGFOOD_KEEP_ACTIVE:-0}"
export TRICHAT_DOGFOOD_REQUIRE_SUCCESS_AGENTS="${TRICHAT_DOGFOOD_REQUIRE_SUCCESS_AGENTS:-3}"
export TRICHAT_DOGFOOD_VERIFY_COMMAND="${TRICHAT_DOGFOOD_VERIFY_COMMAND:-node -e \"process.exit(0)\"}"

node ./scripts/trichat_dogfood.mjs "$@"
